//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectFinal2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISITA
    {
        public string MOTIVO_VISITA { get; set; }
        public Nullable<System.DateTime> FECHA_VISITA { get; set; }
        public Nullable<System.TimeSpan> HORA_ENTRADA { get; set; }
        public Nullable<System.TimeSpan> HORA_SALIDA { get; set; }
        public string NOMBRE_COMPLETO { get; set; }
        public string CONTACTO_RECIBIO { get; set; }
    }
}
